baseURL="http://example.org/"
title="b0rr3g0 tech"
theme="beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[languages]
  [languages.en]
    contentDir= "content/en"
  [languages.es]
    contentDir= "content/es"

[Params]
  subtitle = "Build a beautiful and simple website in minutes"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "David Borrego"
  website = ""
  email = "dbgjerez@gmail.com"
  github = "dbgjerez"
  twitter = "dbgjerez"
  linkedin = "david-borrego-gutiérrez-868a2466"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4
