baseURL="https://blog.dbgjerez.es"
title="b0rr3g0"
subtitle="omg"
theme="beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
googleAnalytics = "G-NL3RYZ5Z31"

[languages]
  [languages.en]
    contentDir= "content/en"
  [languages.es]
    contentDir= "content/es"

[Params]
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "sheep.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "David Borrego"
  website = "https://blog.dbgjerez.es"
  email = "dbgjerez@gmail.com"
  github = "dbgjerez"
  twitter = "dbgjerez"
  linkedin = "david-borrego-gutiérrez-868a2466"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4
